export const SET_REGISTRATION_FORM_TEXT_FIELD_REQUEST = 'SET_REGISTRATION_FORM_TEXT_FIELD_REQUEST';
export const SET_REGISTRATION_FORM_TEXT_FIELD_FAILURE = 'SET_REGISTRATION_FORM_TEXT_FIELD_FAILURE';
export const SET_REGISTRATION_FORM_TEXT_FIELD_SUCCESS = 'SET_REGISTRATION_FORM_TEXT_FIELD_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const SET_LOGIN_FORM_TEXT_FIELD_REQUEST = 'SET_LOGIN_FORM_TEXT_FIELD_REQUEST';
export const SET_LOGIN_FORM_TEXT_FIELD_FAILURE = 'SET_LOGIN_FORM_TEXT_FIELD_FAILURE';
export const SET_LOGIN_FORM_TEXT_FIELD_SUCCESS = 'SET_LOGIN_FORM_TEXT_FIELD_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_AUTH_FORM_IS_VALIDATED = 'SET_AUTH_FORM_IS_VALIDATED';
