export const LOAD_EVENT_LIST_REQUEST = 'LOAD_EVENT_LIST_REQUEST';
export const LOAD_EVENT_LIST_FAILURE = 'LOAD_EVENT_LIST_FAILURE';
export const LOAD_EVENT_LIST_SUCCESS = 'LOAD_EVENT_LIST_SUCCESS';

export const CLEAR_EVENT_LIST = 'CLEAR_EVENT_LIST';

export const LOAD_EVENT_REQUEST = 'LOAD_EVENT_REQUEST';
export const LOAD_EVENT_FAILURE = 'LOAD_EVENT_FAILURE';
export const LOAD_EVENT_SUCCESS = 'LOAD_EVENT_SUCCESS';
